name: API Security- Akto

on:
  push:

jobs:
  akto:
    # User-definable name of this GitHub Actions job:
    name: API security Scan
    # If you are self-hosting, change the following `runs-on` value: 
    runs-on: ubuntu-latest
    steps:
      # Fetch project source with GitHub Actions Checkout.
      - uses: actions/checkout@v3
      
      - name: Run CI/CD tests
        uses: akto-api-security/run-scan@v1.0.3
        with:
          AKTO_DASHBOARD_URL: ${{vars.AKTO_DASHBOARD_URL}}
          AKTO_API_KEY: ${{vars.AKTO_API_KEY}}
          AKTO_TEST_ID: ${{vars.AKTO_TEST_ID}}
          START_TIME_DELAY: 180 # Delay in seconds after which testing run is started, optional, default is 0 
        
